[project]
name = "capp-30239-interactive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.0.0",
    "geojson>=3.2.0",
    "jupyter>=1.1.1",
    "polars>=1.35.2",
]
